name: Deploy Python Function to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'src/ingestion/**'

env:
  AZURE_FUNCTIONAPP_NAME: 'aerocloud-ingestion-espinasse'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. On Checkout le code source
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configuration de l'environnement Python sur le Runner GitHub
    - name: Setup Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # 3. ON SUPPRIME l'étape de création du venv ! 
    # On laisse simplement GitHub packager le dossier src/ingestion tel quel.

    # 4. Le déploiement officiel vers Azure avec le "Remote Build" activé
    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: 'Production'
        package: 'src/ingestion/'
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true